use std::collections::BTreeMap;
use std::fmt::Write;

use crate::names::{insert_unique, kebab, pascal};
use crate::{Definition, Document, Type};

/// Render a method-oriented Calcit client for native bindings.
pub(crate) fn render(document: &Document) -> Result<String, String> {
    let definitions = sorted_definitions(document);
    let mut methods = BTreeMap::new();
    let mut seen = BTreeMap::new();
    for definition in &definitions {
        let method = kebab(&definition.name)?;
        insert_unique(&mut seen, &method, &definition.id, "Calcit method")?;
        validate_symbol(definition)?;
        methods.insert(definition.id.as_str(), method);
    }

    let package = kebab(&document.package)?;
    let namespace = format!("generated.{}.ffi", package.replace('-', "."));
    let type_prefix = pascal(&document.package)?;
    let client_base = format!("{type_prefix}FfiClientBase");
    let client = format!("{type_prefix}FfiClient");
    let trait_name = format!("{type_prefix}FfiMethods");
    let impl_name = format!("{type_prefix}FfiMethodsImpl");
    let mut output = String::new();
    writeln!(
        output,
        "; Generated by calcit-bindgen from Interface IR v{}. Do not edit.\n; Package: {} {}\n\nns {}\n",
        document.version, document.package, document.package_version, namespace
    )
    .expect("write to String");
    writeln!(
        output,
        "def {client_base} $ defstruct {client_base} (:dylib-path 'String)\n"
    )
    .expect("write to String");
    writeln!(output, "def {trait_name} $ deftrait {trait_name}").expect("write to String");
    for definition in &definitions {
        let signature = definition
            .signature
            .as_ref()
            .ok_or_else(|| format!("{} has no supported signature", definition.id))?;
        let mut argument_types = vec![client_base.clone()];
        argument_types.extend(
            signature
                .parameters
                .iter()
                .map(|parameter| render_type(&parameter.type_ir))
                .collect::<Result<Vec<_>, _>>()?,
        );
        writeln!(
            output,
            "  .{} $ :: 'Fn\n    {{}}\n      :generics $ []\n      :args $ [] {}\n      :return {}",
            methods[definition.id.as_str()],
            argument_types.join(" "),
            render_type(&signature.result)?
        )
        .expect("write to String");
    }
    writeln!(
        output,
        "\ndef {impl_name} $ defimpl {impl_name} {trait_name}"
    )
    .expect("write to String");
    for definition in &definitions {
        let method = &methods[definition.id.as_str()];
        let signature = definition
            .signature
            .as_ref()
            .ok_or_else(|| format!("{} has no supported signature", definition.id))?;
        let parameters = (0..signature.parameters.len())
            .map(|index| format!("arg{index}"))
            .collect::<Vec<_>>();
        let arguments = if parameters.is_empty() {
            String::new()
        } else {
            format!(" {}", parameters.join(" "))
        };
        let parameter_list = if parameters.is_empty() {
            "self".to_owned()
        } else {
            format!("self {}", parameters.join(" "))
        };
        let symbol = definition
            .lowering
            .symbol
            .as_deref()
            .expect("validated lowering symbol");
        let result_type = render_type(&signature.result)?;
        writeln!(
            output,
            "  .{method} $ fn ({parameter_list})\n    assert-type self {client_base}\n    assert-type\n      &call-dylib-edn (:dylib-path self) |{symbol}{arguments}\n      {result_type}"
        )
        .expect("write to String");
    }
    writeln!(
        output,
        "\ndef {client} $ impl-traits {client_base} {impl_name}\n\ndefn create-client (dylib-path)\n  %{{}} {client} (:dylib-path dylib-path)"
    )
    .expect("write to String");
    Ok(output)
}

fn render_type(type_ir: &Type) -> Result<String, String> {
    match type_ir {
        Type::Unit => Ok("'Unit".to_owned()),
        Type::Bool => Ok("'Bool".to_owned()),
        Type::Number => Ok("'Number".to_owned()),
        Type::String => Ok("'String".to_owned()),
        Type::Buffer => Ok("'Buffer".to_owned()),
        Type::List { item } => Ok(format!("(:: 'List {})", render_type(item)?)),
        Type::Option { item } => Ok(format!("(:: 'Option {})", render_type(item)?)),
        Type::Result { ok, error } => Ok(format!(
            "(:: 'Result {} {})",
            render_type(ok)?,
            render_type(error)?
        )),
        Type::Struct { id, arguments } | Type::Enum { id, arguments } => {
            if arguments.is_empty() {
                Ok(format!("'{id}"))
            } else {
                Ok(format!(
                    "(:: '{id} {})",
                    arguments
                        .iter()
                        .map(render_type)
                        .collect::<Result<Vec<_>, _>>()?
                        .join(" ")
                ))
            }
        }
        Type::TypeParameter { name } => Err(format!(
            "callable Calcit wrapper cannot expose declaration type parameter {name}"
        )),
    }
}

fn sorted_definitions(document: &Document) -> Vec<&Definition> {
    let mut definitions = document.definitions.iter().collect::<Vec<_>>();
    definitions.sort_by(|left, right| left.id.cmp(&right.id));
    definitions
}

fn validate_symbol(definition: &Definition) -> Result<(), String> {
    let symbol = definition
        .lowering
        .symbol
        .as_deref()
        .ok_or_else(|| format!("{} is missing lowering.symbol", definition.id))?;
    let mut chars = symbol.chars();
    let valid = matches!(chars.next(), Some(first) if first.is_ascii_alphabetic() || first == '_')
        && chars.all(|character| character.is_ascii_alphanumeric() || character == '_');
    if valid {
        Ok(())
    } else {
        Err(format!(
            "{} lowering.symbol {symbol:?} is not a portable native symbol",
            definition.id
        ))
    }
}
