use std::collections::BTreeMap;

use crate::{
    ComponentDirection, ComponentDocument, ComponentInvocation, Declaration, DefinitionStatus,
    StructField, Type,
};

const CLIENT_INSTANCE: &str = "calcit:wasi-http/client";
const REQUEST_FUNCTION: &str = "request";

const ADAPTER: &str = r#"// Generated by calcit-bindgen. Do not edit.
// Enable calcit-bindgen's `wasmtime-http` feature in the host crate.

pub use calcit_bindgen::wasmtime_http::{
    HttpBody, HttpError, HttpHeader, HttpMethod, HttpRequest, HttpResponse, WasiHttpConfig,
    add_to_linker, send,
};
"#;

pub(crate) fn render(document: &ComponentDocument) -> Result<Option<String>, String> {
    let candidates = document
        .definitions
        .iter()
        .filter(|definition| {
            definition.module.as_deref() == Some(CLIENT_INSTANCE)
                && definition.symbol == REQUEST_FUNCTION
        })
        .collect::<Vec<_>>();
    if candidates.is_empty() {
        return Ok(None);
    }
    if candidates.len() != 1 {
        return Err(format!(
            "{CLIENT_INSTANCE}.{REQUEST_FUNCTION} must be declared exactly once"
        ));
    }
    let definition = candidates[0];
    if definition.direction != ComponentDirection::Import
        || definition.invocation != Some(ComponentInvocation::Async)
        || definition.status != DefinitionStatus::Supported
    {
        return Err(format!(
            "{} must be a supported async Component import",
            definition.id
        ));
    }
    let signature = definition.signature.as_ref().ok_or_else(|| {
        format!(
            "{} must provide the closed buffered HTTP signature",
            definition.id
        )
    })?;
    if signature.parameters.len() != 1 || signature.parameters[0].position != 0 {
        return Err(format!(
            "{} must accept exactly one HttpRequest parameter",
            definition.id
        ));
    }
    let request_id = nominal_id(&signature.parameters[0].type_ir, "struct", &definition.id)?;
    let (response_id, error_id) = match &signature.result {
        Type::Result { ok, error } => (
            nominal_id(ok, "struct", &definition.id)?,
            nominal_id(error, "enum", &definition.id)?,
        ),
        _ => {
            return Err(format!(
                "{} must return Result<HttpResponse, HttpError>",
                definition.id
            ));
        }
    };
    let declarations = document
        .declarations
        .iter()
        .map(|declaration| (declaration.id(), declaration))
        .collect::<BTreeMap<_, _>>();
    let request = struct_fields(&declarations, request_id, "HttpRequest")?;
    let response = struct_fields(&declarations, response_id, "HttpResponse")?;
    let error = enum_variants(&declarations, error_id, "HttpError")?;

    let method_id = field_nominal(request, "method", "enum")?;
    let header_id = list_item_nominal(field(request, "headers")?, "struct", "HttpRequest.headers")?;
    let body_id = field_nominal(request, "body", "enum")?;
    require_fields(
        request,
        &[
            ("body", nominal_enum(body_id)),
            ("headers", list(nominal_struct(header_id))),
            ("max-response-bytes", Type::Uint64),
            ("method", nominal_enum(method_id)),
            ("url", Type::String),
        ],
        "HttpRequest",
    )?;
    require_fields(
        struct_fields(&declarations, header_id, "HttpHeader")?,
        &[("name", Type::String), ("value", Type::Buffer)],
        "HttpHeader",
    )?;
    require_fields(
        response,
        &[
            ("body", nominal_enum(body_id)),
            ("headers", list(nominal_struct(header_id))),
            ("status", Type::Uint16),
        ],
        "HttpResponse",
    )?;
    require_variants(
        enum_variants(&declarations, method_id, "HttpMethod")?,
        &[
            ("delete", vec![]),
            ("get", vec![]),
            ("head", vec![]),
            ("options", vec![]),
            ("patch", vec![]),
            ("post", vec![]),
            ("put", vec![]),
        ],
        "HttpMethod",
    )?;
    require_variants(
        enum_variants(&declarations, body_id, "HttpBody")?,
        &[
            ("bytes", vec![Type::Buffer]),
            ("empty", vec![]),
            ("text", vec![Type::String]),
        ],
        "HttpBody",
    )?;
    require_variants(
        error,
        &[
            ("capability-denied", vec![Type::String]),
            ("invalid-request", vec![Type::String]),
            ("response-too-large", vec![Type::Uint64]),
            ("transport", vec![Type::String]),
            ("unsupported", vec![Type::String]),
        ],
        "HttpError",
    )?;
    Ok(Some(ADAPTER.to_owned()))
}

fn nominal_id<'a>(value: &'a Type, kind: &str, path: &str) -> Result<&'a str, String> {
    match (kind, value) {
        ("struct", Type::Struct { id, arguments }) | ("enum", Type::Enum { id, arguments })
            if arguments.is_empty() =>
        {
            Ok(id)
        }
        _ => Err(format!("{path} must reference a monomorphic {kind}")),
    }
}

fn struct_fields<'a>(
    declarations: &BTreeMap<&str, &'a Declaration>,
    id: &str,
    expected_name: &str,
) -> Result<&'a [StructField], String> {
    match declarations.get(id) {
        Some(Declaration::Struct {
            name,
            type_parameters,
            fields,
            ..
        }) if name == expected_name && type_parameters.is_empty() => Ok(fields),
        _ => Err(format!(
            "{CLIENT_INSTANCE}.{REQUEST_FUNCTION} requires a monomorphic {expected_name} struct at {id}"
        )),
    }
}

fn enum_variants<'a>(
    declarations: &BTreeMap<&str, &'a Declaration>,
    id: &str,
    expected_name: &str,
) -> Result<&'a [crate::EnumVariant], String> {
    match declarations.get(id) {
        Some(Declaration::Enum {
            name,
            type_parameters,
            variants,
            ..
        }) if name == expected_name && type_parameters.is_empty() => Ok(variants),
        _ => Err(format!(
            "{CLIENT_INSTANCE}.{REQUEST_FUNCTION} requires a monomorphic {expected_name} enum at {id}"
        )),
    }
}

fn field<'a>(fields: &'a [StructField], name: &str) -> Result<&'a Type, String> {
    fields
        .iter()
        .find(|field| field.name == name)
        .map(|field| &field.type_ir)
        .ok_or_else(|| format!("closed HTTP contract is missing field {name:?}"))
}

fn field_nominal<'a>(fields: &'a [StructField], name: &str, kind: &str) -> Result<&'a str, String> {
    nominal_id(field(fields, name)?, kind, name)
}

fn list_item_nominal<'a>(value: &'a Type, kind: &str, path: &str) -> Result<&'a str, String> {
    match value {
        Type::List { item } => nominal_id(item, kind, path),
        _ => Err(format!("{path} must be a list of monomorphic {kind}")),
    }
}

fn nominal_struct(id: &str) -> Type {
    Type::Struct {
        id: id.to_owned(),
        arguments: vec![],
    }
}

fn nominal_enum(id: &str) -> Type {
    Type::Enum {
        id: id.to_owned(),
        arguments: vec![],
    }
}

fn list(item: Type) -> Type {
    Type::List {
        item: Box::new(item),
    }
}

fn require_fields(
    actual: &[StructField],
    expected: &[(&str, Type)],
    name: &str,
) -> Result<(), String> {
    if actual.len() != expected.len()
        || actual
            .iter()
            .zip(expected)
            .any(|(field, (field_name, field_type))| {
                field.name != *field_name || field.type_ir != *field_type
            })
    {
        return Err(format!(
            "{name} does not match the closed buffered HTTP contract"
        ));
    }
    Ok(())
}

fn require_variants(
    actual: &[crate::EnumVariant],
    expected: &[(&str, Vec<Type>)],
    name: &str,
) -> Result<(), String> {
    if actual.len() != expected.len()
        || actual
            .iter()
            .zip(expected)
            .any(|(variant, (variant_name, payload))| {
                variant.name != *variant_name || variant.payload != *payload
            })
    {
        return Err(format!(
            "{name} does not match the closed buffered HTTP contract"
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use crate::{ComponentDefinition, EnumVariant, FunctionSignature, Parameter, StructField};

    use super::*;

    fn struct_type(id: &str) -> Type {
        Type::Struct {
            id: id.to_owned(),
            arguments: vec![],
        }
    }

    fn enum_type(id: &str) -> Type {
        Type::Enum {
            id: id.to_owned(),
            arguments: vec![],
        }
    }

    fn variant(name: &str, payload: Vec<Type>) -> EnumVariant {
        EnumVariant {
            name: name.to_owned(),
            payload,
        }
    }

    fn declaration_struct(name: &str, fields: Vec<(&str, Type)>) -> Declaration {
        Declaration::Struct {
            id: format!("demo.main/{name}"),
            namespace: "demo.main".to_owned(),
            name: name.to_owned(),
            type_parameters: vec![],
            fields: fields
                .into_iter()
                .map(|(name, type_ir)| StructField {
                    name: name.to_owned(),
                    type_ir,
                })
                .collect(),
        }
    }

    fn declaration_enum(name: &str, variants: Vec<EnumVariant>) -> Declaration {
        Declaration::Enum {
            id: format!("demo.main/{name}"),
            namespace: "demo.main".to_owned(),
            name: name.to_owned(),
            type_parameters: vec![],
            variants,
        }
    }

    fn document() -> ComponentDocument {
        let method = "demo.main/HttpMethod";
        let header = "demo.main/HttpHeader";
        let body = "demo.main/HttpBody";
        let request = "demo.main/HttpRequest";
        let response = "demo.main/HttpResponse";
        let error = "demo.main/HttpError";
        ComponentDocument {
            version: 3,
            package: "demo".to_owned(),
            package_version: "0.0.0".to_owned(),
            declarations: vec![
                declaration_enum(
                    "HttpMethod",
                    ["delete", "get", "head", "options", "patch", "post", "put"]
                        .into_iter()
                        .map(|name| variant(name, vec![]))
                        .collect(),
                ),
                declaration_struct(
                    "HttpHeader",
                    vec![("name", Type::String), ("value", Type::Buffer)],
                ),
                declaration_enum(
                    "HttpBody",
                    vec![
                        variant("bytes", vec![Type::Buffer]),
                        variant("empty", vec![]),
                        variant("text", vec![Type::String]),
                    ],
                ),
                declaration_struct(
                    "HttpRequest",
                    vec![
                        ("body", enum_type(body)),
                        (
                            "headers",
                            Type::List {
                                item: Box::new(struct_type(header)),
                            },
                        ),
                        ("max-response-bytes", Type::Uint64),
                        ("method", enum_type(method)),
                        ("url", Type::String),
                    ],
                ),
                declaration_struct(
                    "HttpResponse",
                    vec![
                        ("body", enum_type(body)),
                        (
                            "headers",
                            Type::List {
                                item: Box::new(struct_type(header)),
                            },
                        ),
                        ("status", Type::Uint16),
                    ],
                ),
                declaration_enum(
                    "HttpError",
                    vec![
                        variant("capability-denied", vec![Type::String]),
                        variant("invalid-request", vec![Type::String]),
                        variant("response-too-large", vec![Type::Uint64]),
                        variant("transport", vec![Type::String]),
                        variant("unsupported", vec![Type::String]),
                    ],
                ),
            ],
            definitions: vec![ComponentDefinition {
                id: "demo.main/host-http-request".to_owned(),
                namespace: "demo.main".to_owned(),
                name: "host-http-request".to_owned(),
                doc: String::new(),
                logical_schema: String::new(),
                direction: ComponentDirection::Import,
                invocation: Some(ComponentInvocation::Async),
                module: Some(CLIENT_INSTANCE.to_owned()),
                symbol: REQUEST_FUNCTION.to_owned(),
                signature: Some(FunctionSignature {
                    parameters: vec![Parameter {
                        position: 0,
                        type_ir: struct_type(request),
                    }],
                    result: Type::Result {
                        ok: Box::new(struct_type(response)),
                        error: Box::new(enum_type(error)),
                    },
                }),
                status: DefinitionStatus::Supported,
                diagnostic_codes: vec![],
            }],
        }
    }

    #[test]
    fn recognizes_only_the_closed_http_contract() {
        assert_eq!(
            render(&document()).expect("render adapter"),
            Some(ADAPTER.to_owned())
        );

        let mut drifted = document();
        let Declaration::Struct { fields, .. } = &mut drifted.declarations[3] else {
            panic!("HttpRequest fixture must be a struct")
        };
        fields.retain(|field| field.name != "max-response-bytes");
        assert!(
            render(&drifted)
                .expect_err("reject contract drift")
                .contains("HttpRequest")
        );

        let mut reordered = document();
        let Declaration::Struct { fields, .. } = &mut reordered.declarations[3] else {
            panic!("HttpRequest fixture must be a struct")
        };
        fields.swap(0, 1);
        assert!(
            render(&reordered)
                .expect_err("reject ABI field reordering")
                .contains("HttpRequest")
        );
    }
}
