use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::{Declaration, Definition, Document, Type};

/// Render strict synchronous `edn-buffer-v1` Rust bindings.
pub(crate) fn render(document: &Document) -> Result<String, String> {
    validate_lowerings(document)?;
    let names = RustNames::new(document)?;
    let mut output = String::new();
    writeln!(
        output,
        "// Generated by calcit-bindgen from Interface IR v{}. Do not edit.\n// Package: {} {}\n",
        document.version, document.package, document.package_version
    )
    .expect("write to String");
    output.push_str(CODEC_PRELUDE);

    for declaration in &document.declarations {
        render_declaration(&mut output, declaration, &names)?;
    }
    render_service_trait(&mut output, document, &names)?;
    for definition in &document.definitions {
        render_adapter(&mut output, definition, &names)?;
    }
    render_export_macro(&mut output, document, &names)?;
    Ok(output)
}

struct RustNames {
    types: BTreeMap<String, String>,
    methods: BTreeMap<String, String>,
    exports: BTreeMap<String, String>,
    service: String,
    export_macro: String,
}

impl RustNames {
    fn new(document: &Document) -> Result<Self, String> {
        let mut types = BTreeMap::new();
        let mut methods = BTreeMap::new();
        let mut exports = BTreeMap::new();
        let mut seen_types = BTreeMap::new();
        let mut seen_methods = BTreeMap::new();
        let mut seen_exports = BTreeMap::new();
        for declaration in &document.declarations {
            let name = upper_name(declaration.id());
            insert_unique(&mut seen_types, &name, declaration.id(), "Rust type")?;
            types.insert(declaration.id().to_owned(), name);
        }
        for definition in &document.definitions {
            let method = lower_name(&definition.id);
            insert_unique(&mut seen_methods, &method, &definition.id, "Rust method")?;
            methods.insert(definition.id.clone(), method);

            let symbol = definition
                .lowering
                .symbol
                .as_deref()
                .ok_or_else(|| format!("{} is missing lowering.symbol", definition.id))?;
            if !is_plain_rust_identifier(symbol) || is_rust_keyword(symbol) {
                return Err(format!(
                    "{} lowering symbol {symbol:?} cannot form the required buffer ABI export; use a lowercase ASCII Rust identifier",
                    definition.id
                ));
            }
            let export = format!("{symbol}_calcit_ffi_v1");
            insert_unique(&mut seen_exports, &export, &definition.id, "ABI export")?;
            exports.insert(definition.id.clone(), export);
        }
        Ok(Self {
            types,
            methods,
            exports,
            service: format!("{}Ffi", upper_name(&document.package)),
            export_macro: format!("export_{}_ffi", lower_name(&document.package)),
        })
    }
}

fn insert_unique(
    seen: &mut BTreeMap<String, String>,
    generated: &str,
    id: &str,
    category: &str,
) -> Result<(), String> {
    if let Some(previous) = seen.insert(generated.to_owned(), id.to_owned()) {
        return Err(format!(
            "{category} name collision: {previous} and {id} both map to {generated}"
        ));
    }
    Ok(())
}

fn validate_lowerings(document: &Document) -> Result<(), String> {
    let mut unsupported = Vec::new();
    for definition in &document.definitions {
        let lowering = &definition.lowering;
        if lowering.backend.as_deref() != Some("native")
            || lowering.invoke.as_deref() != Some("sync")
            || lowering.transport.as_deref() != Some("edn-buffer-v1")
        {
            unsupported.push(format!(
                "{} (backend={}, invoke={}, transport={})",
                definition.id,
                lowering.backend.as_deref().unwrap_or("missing"),
                lowering.invoke.as_deref().unwrap_or("missing"),
                lowering.transport.as_deref().unwrap_or("missing")
            ));
        }
    }
    if unsupported.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "Rust generation supports only native + sync + edn-buffer-v1 definitions; unsupported: {}",
            unsupported.join(", ")
        ))
    }
}

fn render_declaration(
    output: &mut String,
    declaration: &Declaration,
    names: &RustNames,
) -> Result<(), String> {
    match declaration {
        Declaration::Struct {
            id,
            type_parameters,
            fields,
            ..
        } => {
            let parameters = render_parameters(type_parameters);
            writeln!(output, "#[derive(Debug, Clone, PartialEq)]").expect("write to String");
            writeln!(output, "pub struct {}{} {{", names.types[id], parameters)
                .expect("write to String");
            let mut seen = BTreeSet::new();
            for field in fields {
                let name = lower_name(&field.name);
                if !seen.insert(name.clone()) {
                    return Err(format!("Rust field name collision in {id}: {}", field.name));
                }
                writeln!(
                    output,
                    "    pub {name}: {},",
                    render_type(&field.type_ir, names)?
                )
                .expect("write to String");
            }
            output.push_str("}\n\n");
            render_struct_codec(output, declaration, names)?;
        }
        Declaration::Enum {
            id,
            type_parameters,
            variants,
            ..
        } => {
            let parameters = render_parameters(type_parameters);
            writeln!(output, "#[derive(Debug, Clone, PartialEq)]").expect("write to String");
            writeln!(output, "pub enum {}{} {{", names.types[id], parameters)
                .expect("write to String");
            let mut seen = BTreeSet::new();
            for variant in variants {
                let name = upper_name(&variant.name);
                if !seen.insert(name.clone()) {
                    return Err(format!(
                        "Rust variant name collision in {id}: {}",
                        variant.name
                    ));
                }
                if variant.payload.is_empty() {
                    writeln!(output, "    {name},").expect("write to String");
                } else {
                    let payload = variant
                        .payload
                        .iter()
                        .map(|item| render_type(item, names))
                        .collect::<Result<Vec<_>, _>>()?
                        .join(", ");
                    writeln!(output, "    {name}({payload}),").expect("write to String");
                }
            }
            output.push_str("}\n\n");
            render_enum_codec(output, declaration, names)?;
        }
    }
    Ok(())
}

fn render_struct_codec(
    output: &mut String,
    declaration: &Declaration,
    names: &RustNames,
) -> Result<(), String> {
    let Declaration::Struct {
        id,
        name,
        type_parameters,
        fields,
        ..
    } = declaration
    else {
        unreachable!()
    };
    let (impl_parameters, type_parameters_rendered, bounds) = codec_generics(type_parameters);
    writeln!(
        output,
        "impl{impl_parameters} CalcitEdnCodec for {}{type_parameters_rendered}{bounds} {{",
        names.types[id]
    )
    .expect("write to String");
    output.push_str(
        "    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String> {\n",
    );
    output.push_str("        let cirru_edn::Edn::Struct(record) = value else { return Err(calcit_kind_error(path, \"struct\", &value)); };\n");
    writeln!(
        output,
        "        if record.name.as_ref() != {:?} {{ return Err(format!(\"{{path}}: expected struct {}, got {{}}\", record.name)); }}",
        name, name
    )
    .expect("write to String");
    writeln!(output, "        if record.pairs.len() != {} {{ return Err(format!(\"{{path}}: struct {} expects {} field(s), got {{}}\", record.pairs.len())); }}", fields.len(), name, fields.len()).expect("write to String");
    output.push_str("        let mut fields = calcit_fields(record.pairs, path)?;\n");
    for field in fields {
        let rust_name = lower_name(&field.name);
        writeln!(output, "        let {rust_name} = calcit_take_field(&mut fields, {:?}, path).and_then(|value| CalcitEdnCodec::decode_edn(value, &format!(\"{{path}}.{}\")))?;", field.name, field.name).expect("write to String");
    }
    output.push_str("        if let Some((field, _)) = fields.into_iter().next() { return Err(format!(\"{path}: unexpected field :{field}\")); }\n");
    write!(output, "        Ok(Self {{ ").expect("write to String");
    for (index, field) in fields.iter().enumerate() {
        if index > 0 {
            output.push_str(", ");
        }
        output.push_str(&lower_name(&field.name));
    }
    output.push_str(" })\n    }\n\n    fn encode_edn(self) -> cirru_edn::Edn {\n");
    writeln!(
        output,
        "        let mut record = cirru_edn::EdnStructView::new({name:?});"
    )
    .expect("write to String");
    for field in fields {
        writeln!(
            output,
            "        record.insert({:?}, self.{}.encode_edn());",
            field.name,
            lower_name(&field.name)
        )
        .expect("write to String");
    }
    output.push_str("        cirru_edn::Edn::Struct(record)\n    }\n}\n\n");
    Ok(())
}

fn render_enum_codec(
    output: &mut String,
    declaration: &Declaration,
    names: &RustNames,
) -> Result<(), String> {
    let Declaration::Enum {
        id,
        name,
        type_parameters,
        variants,
        ..
    } = declaration
    else {
        unreachable!()
    };
    let (impl_parameters, type_parameters_rendered, bounds) = codec_generics(type_parameters);
    writeln!(
        output,
        "impl{impl_parameters} CalcitEdnCodec for {}{type_parameters_rendered}{bounds} {{",
        names.types[id]
    )
    .expect("write to String");
    output.push_str(
        "    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String> {\n",
    );
    output.push_str("        let cirru_edn::Edn::Enum(value) = value else { return Err(calcit_kind_error(path, \"enum\", &value)); };\n");
    writeln!(output, "        if value.type_name.as_deref() != Some({name:?}) {{ return Err(format!(\"{{path}}: expected enum {}, got {{:?}}\", value.type_name)); }}", name).expect("write to String");
    output.push_str("        match value.variant.as_ref() {\n");
    for variant in variants {
        let rust_name = upper_name(&variant.name);
        writeln!(output, "            {:?} => {{", variant.name).expect("write to String");
        writeln!(output, "                if value.extra.len() != {} {{ return Err(format!(\"{{path}}: variant :{} expects {} payload(s), got {{}}\", value.extra.len())); }}", variant.payload.len(), variant.name, variant.payload.len()).expect("write to String");
        output.push_str("                let mut payload = value.extra.into_iter();\n");
        for (index, _) in variant.payload.iter().enumerate() {
            writeln!(output, "                let value{index} = CalcitEdnCodec::decode_edn(payload.next().expect(\"validated payload length\"), &format!(\"{{path}}.payload[{index}]\"))?;").expect("write to String");
        }
        if variant.payload.is_empty() {
            writeln!(output, "                Ok(Self::{rust_name})").expect("write to String");
        } else {
            let values = (0..variant.payload.len())
                .map(|index| format!("value{index}"))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(output, "                Ok(Self::{rust_name}({values}))")
                .expect("write to String");
        }
        output.push_str("            }\n");
    }
    writeln!(
        output,
        "            variant => Err(format!(\"{{path}}: enum {} has no variant :{{variant}}\")),",
        name
    )
    .expect("write to String");
    output.push_str(
        "        }\n    }\n\n    fn encode_edn(self) -> cirru_edn::Edn {\n        match self {\n",
    );
    for variant in variants {
        let rust_name = upper_name(&variant.name);
        if variant.payload.is_empty() {
            writeln!(output, "            Self::{rust_name} => cirru_edn::Edn::typed_enum({name:?}, {:?}, vec![]),", variant.name).expect("write to String");
        } else {
            let values = (0..variant.payload.len())
                .map(|index| format!("value{index}"))
                .collect::<Vec<_>>();
            let encoded = values
                .iter()
                .map(|value| format!("{value}.encode_edn()"))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(output, "            Self::{rust_name}({}) => cirru_edn::Edn::typed_enum({name:?}, {:?}, vec![{encoded}]),", values.join(", "), variant.name).expect("write to String");
        }
    }
    output.push_str("        }\n    }\n}\n\n");
    Ok(())
}

fn render_service_trait(
    output: &mut String,
    document: &Document,
    names: &RustNames,
) -> Result<(), String> {
    writeln!(
        output,
        "/// Typed business implementation consumed by the generated FFI exports."
    )
    .expect("write to String");
    writeln!(output, "pub trait {} {{", names.service).expect("write to String");
    for definition in &document.definitions {
        let signature = definition
            .signature
            .as_ref()
            .ok_or_else(|| format!("{} has no supported signature", definition.id))?;
        write!(output, "    fn {}(&self", names.methods[&definition.id]).expect("write to String");
        for parameter in &signature.parameters {
            write!(
                output,
                ", arg{}: {}",
                parameter.position,
                render_type(&parameter.type_ir, names)?
            )
            .expect("write to String");
        }
        writeln!(
            output,
            ") -> Result<{}, String>;",
            render_type(&signature.result, names)?
        )
        .expect("write to String");
    }
    output.push_str("}\n\n");
    Ok(())
}

fn render_adapter(
    output: &mut String,
    definition: &Definition,
    names: &RustNames,
) -> Result<(), String> {
    let signature = definition
        .signature
        .as_ref()
        .ok_or_else(|| format!("{} has no supported signature", definition.id))?;
    let adapter = format!("{}_calcit_typed_adapter", names.methods[&definition.id]);
    writeln!(output, "#[doc(hidden)]").expect("write to String");
    writeln!(output, "pub fn {adapter}<T: {} + ?Sized>(service: &T, args: Vec<cirru_edn::Edn>) -> Result<cirru_edn::Edn, String> {{", names.service).expect("write to String");
    writeln!(
        output,
        "    if args.len() != {} {{ return Err(format!({:?}, args.len())); }}",
        signature.parameters.len(),
        format!(
            "{} expects {} argument(s), got {{}}",
            definition.id,
            signature.parameters.len()
        )
    )
    .expect("write to String");
    output.push_str("    let mut args = args.into_iter();\n");
    for parameter in &signature.parameters {
        writeln!(output, "    let arg{}: {} = CalcitEdnCodec::decode_edn(args.next().expect(\"validated argument length\"), {:?})?;", parameter.position, render_type(&parameter.type_ir, names)?, format!("{} argument {}", definition.id, parameter.position)).expect("write to String");
    }
    let arguments = signature
        .parameters
        .iter()
        .map(|parameter| format!("arg{}", parameter.position))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        output,
        "    service.{}({arguments}).map(CalcitEdnCodec::encode_edn)",
        names.methods[&definition.id]
    )
    .expect("write to String");
    output.push_str("}\n\n");
    Ok(())
}

fn render_export_macro(
    output: &mut String,
    document: &Document,
    names: &RustNames,
) -> Result<(), String> {
    writeln!(
        output,
        "/// Export the generated buffer ABI and bind every method to one service expression."
    )
    .expect("write to String");
    writeln!(output, "#[macro_export]").expect("write to String");
    writeln!(output, "macro_rules! {} {{", names.export_macro).expect("write to String");
    output.push_str(
        "    ($service:expr) => {\n        calcit_native_ffi::export_buffer_abi_v1!();\n",
    );
    for definition in &document.definitions {
        let method = &names.methods[&definition.id];
        let callback = format!("{method}_calcit_export_adapter");
        writeln!(
            output,
            "        fn {callback}(args: Vec<cirru_edn::Edn>) -> Result<cirru_edn::Edn, String> {{"
        )
        .expect("write to String");
        writeln!(
            output,
            "            $crate::{method}_calcit_typed_adapter(&$service, args)"
        )
        .expect("write to String");
        output.push_str("        }\n");
        writeln!(
            output,
            "        calcit_native_ffi::export_edn_buffer_method_v1!({}, {callback});",
            names.exports[&definition.id]
        )
        .expect("write to String");
    }
    output.push_str("    };\n}\n");
    Ok(())
}

fn render_type(type_ir: &Type, names: &RustNames) -> Result<String, String> {
    match type_ir {
        Type::Unit => Ok("()".to_owned()),
        Type::Bool => Ok("bool".to_owned()),
        Type::Number => Ok("f64".to_owned()),
        Type::String => Ok("String".to_owned()),
        Type::Buffer => Ok("CalcitBuffer".to_owned()),
        Type::List { item } => Ok(format!("Vec<{}>", render_type(item, names)?)),
        Type::Option { item } => Ok(format!("Option<{}>", render_type(item, names)?)),
        Type::Result { ok, error } => Ok(format!(
            "Result<{}, {}>",
            render_type(ok, names)?,
            render_type(error, names)?
        )),
        Type::Struct { id, arguments } | Type::Enum { id, arguments } => {
            let name = names
                .types
                .get(id)
                .ok_or_else(|| format!("missing Rust name for declaration {id}"))?;
            if arguments.is_empty() {
                Ok(name.clone())
            } else {
                Ok(format!(
                    "{name}<{}>",
                    arguments
                        .iter()
                        .map(|argument| render_type(argument, names))
                        .collect::<Result<Vec<_>, _>>()?
                        .join(", ")
                ))
            }
        }
        Type::TypeParameter { name } => Ok(upper_name(name)),
    }
}

fn render_parameters(parameters: &[String]) -> String {
    if parameters.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            parameters
                .iter()
                .map(|name| upper_name(name))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn codec_generics(parameters: &[String]) -> (String, String, String) {
    if parameters.is_empty() {
        return (String::new(), String::new(), String::new());
    }
    let names = parameters
        .iter()
        .map(|name| upper_name(name))
        .collect::<Vec<_>>();
    (
        format!("<{}>", names.join(", ")),
        format!("<{}>", names.join(", ")),
        format!(
            " where {}",
            names
                .iter()
                .map(|name| format!("{name}: CalcitEdnCodec"))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    )
}

fn words(value: &str) -> Vec<String> {
    let mut words = Vec::new();
    let mut current = String::new();
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if character.is_ascii_uppercase()
                && current
                    .chars()
                    .last()
                    .is_some_and(|previous| previous.is_ascii_lowercase())
            {
                words.push(std::mem::take(&mut current));
            }
            current.push(character.to_ascii_lowercase());
        } else if !current.is_empty() {
            words.push(std::mem::take(&mut current));
        }
    }
    if !current.is_empty() {
        words.push(current);
    }
    if words.is_empty() {
        words.push("value".to_owned());
    }
    words
}

fn upper_name(value: &str) -> String {
    let mut output = String::new();
    for word in words(value) {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            output.push(first.to_ascii_uppercase());
            output.extend(chars);
        }
    }
    if output.starts_with(|character: char| character.is_ascii_digit()) {
        output.insert_str(0, "Calcit");
    }
    output
}

fn lower_name(value: &str) -> String {
    let mut output = words(value).join("_");
    if output.starts_with(|character: char| character.is_ascii_digit()) || is_rust_keyword(&output)
    {
        output.insert_str(0, "calcit_");
    }
    output
}

fn is_plain_rust_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|first| first == '_' || first.is_ascii_alphabetic())
        && chars.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

fn is_rust_keyword(value: &str) -> bool {
    matches!(
        value,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    )
}

const CODEC_PRELUDE: &str = r#"/// Internal typed Cirru EDN conversion contract used by generated adapters.
pub trait CalcitEdnCodec: Sized {
    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String>;
    fn encode_edn(self) -> cirru_edn::Edn;
}

fn calcit_kind_error(path: &str, expected: &str, value: &cirru_edn::Edn) -> String {
    format!("{path}: expected {expected}, got {}", value.type_name())
}

#[allow(dead_code)]
fn calcit_fields(
    fields: Vec<(cirru_edn::EdnTag, cirru_edn::Edn)>,
    path: &str,
) -> Result<std::collections::BTreeMap<String, cirru_edn::Edn>, String> {
    let mut output = std::collections::BTreeMap::new();
    for (name, value) in fields {
        let name = name.ref_str().to_owned();
        if output.insert(name.clone(), value).is_some() {
            return Err(format!("{path}: duplicate field :{name}"));
        }
    }
    Ok(output)
}

#[allow(dead_code)]
fn calcit_take_field(
    fields: &mut std::collections::BTreeMap<String, cirru_edn::Edn>,
    expected: &str,
    path: &str,
) -> Result<cirru_edn::Edn, String> {
    fields
        .remove(expected)
        .ok_or_else(|| format!("{path}: missing field :{expected}"))
}

impl CalcitEdnCodec for () {
    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String> {
        if matches!(value, cirru_edn::Edn::Nil) { Ok(()) } else { Err(calcit_kind_error(path, "unit/nil", &value)) }
    }
    fn encode_edn(self) -> cirru_edn::Edn { cirru_edn::Edn::Nil }
}

impl CalcitEdnCodec for bool {
    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String> {
        if let cirru_edn::Edn::Bool(value) = value { Ok(value) } else { Err(calcit_kind_error(path, "bool", &value)) }
    }
    fn encode_edn(self) -> cirru_edn::Edn { cirru_edn::Edn::Bool(self) }
}

impl CalcitEdnCodec for f64 {
    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String> {
        if let cirru_edn::Edn::Number(value) = value { Ok(value) } else { Err(calcit_kind_error(path, "number", &value)) }
    }
    fn encode_edn(self) -> cirru_edn::Edn { cirru_edn::Edn::Number(self) }
}

impl CalcitEdnCodec for String {
    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String> {
        if let cirru_edn::Edn::Str(value) = value { Ok(value.to_string()) } else { Err(calcit_kind_error(path, "string", &value)) }
    }
    fn encode_edn(self) -> cirru_edn::Edn { cirru_edn::Edn::str(self) }
}

/// Owned bytes transported as a Calcit Buffer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CalcitBuffer(pub Vec<u8>);

impl CalcitEdnCodec for CalcitBuffer {
    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String> {
        if let cirru_edn::Edn::Buffer(value) = value { Ok(Self(value)) } else { Err(calcit_kind_error(path, "buffer", &value)) }
    }
    fn encode_edn(self) -> cirru_edn::Edn { cirru_edn::Edn::Buffer(self.0) }
}

impl<T: CalcitEdnCodec> CalcitEdnCodec for Vec<T> {
    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String> {
        let cirru_edn::Edn::List(cirru_edn::EdnListView(values)) = value else { return Err(calcit_kind_error(path, "list", &value)); };
        values.into_iter().enumerate().map(|(index, value)| T::decode_edn(value, &format!("{path}[{index}]"))).collect()
    }
    fn encode_edn(self) -> cirru_edn::Edn {
        cirru_edn::Edn::List(cirru_edn::EdnListView(self.into_iter().map(CalcitEdnCodec::encode_edn).collect()))
    }
}

impl<T: CalcitEdnCodec> CalcitEdnCodec for Option<T> {
    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String> {
        let cirru_edn::Edn::Enum(value) = value else { return Err(calcit_kind_error(path, "Option", &value)); };
        if value.type_name.as_deref() != Some("Option") { return Err(format!("{path}: expected Option enum, got {:?}", value.type_name)); }
        match (value.variant.as_ref(), value.extra.as_slice()) {
            ("none", []) => Ok(None),
            ("some", [_]) => Ok(Some(T::decode_edn(value.extra.into_iter().next().expect("one payload"), &format!("{path}.some"))?)),
            (variant, extra) => Err(format!("{path}: invalid Option variant :{variant} with {} payload(s)", extra.len())),
        }
    }
    fn encode_edn(self) -> cirru_edn::Edn {
        match self {
            None => cirru_edn::Edn::typed_enum("Option", "none", vec![]),
            Some(value) => cirru_edn::Edn::typed_enum("Option", "some", vec![value.encode_edn()]),
        }
    }
}

impl<T: CalcitEdnCodec, E: CalcitEdnCodec> CalcitEdnCodec for Result<T, E> {
    fn decode_edn(value: cirru_edn::Edn, path: &str) -> Result<Self, String> {
        let cirru_edn::Edn::Enum(value) = value else { return Err(calcit_kind_error(path, "Result", &value)); };
        if value.type_name.as_deref() != Some("Result") { return Err(format!("{path}: expected Result enum, got {:?}", value.type_name)); }
        if value.extra.len() != 1 { return Err(format!("{path}: Result expects one payload, got {}", value.extra.len())); }
        let payload = value.extra.into_iter().next().expect("validated payload length");
        match value.variant.as_ref() {
            "ok" => Ok(Ok(T::decode_edn(payload, &format!("{path}.ok"))?)),
            "err" => Ok(Err(E::decode_edn(payload, &format!("{path}.err"))?)),
            variant => Err(format!("{path}: invalid Result variant :{variant}")),
        }
    }
    fn encode_edn(self) -> cirru_edn::Edn {
        match self {
            Ok(value) => cirru_edn::Edn::typed_enum("Result", "ok", vec![value.encode_edn()]),
            Err(error) => cirru_edn::Edn::typed_enum("Result", "err", vec![error.encode_edn()]),
        }
    }
}

"#;
