use std::collections::BTreeMap;
use std::fmt::Write;

use crate::names::{insert_unique, pascal, snake, type_parameter};
use crate::{Declaration, Document, Type};

pub(crate) fn render(document: &Document) -> Result<String, String> {
    let names = TypeScriptNames::new(document)?;
    let mut output = String::new();
    writeln!(
        output,
        "// Generated by calcit-bindgen from Interface IR v{}. Do not edit.\n// Package: {} {}\n",
        document.version, document.package, document.package_version
    )
    .expect("write to String");
    let mut declarations = document.declarations.iter().collect::<Vec<_>>();
    declarations.sort_by(|left, right| left.id().cmp(right.id()));
    for declaration in declarations {
        render_declaration(&mut output, declaration, &names)?;
    }
    let mut definitions = document.definitions.iter().collect::<Vec<_>>();
    definitions.sort_by(|left, right| left.id.cmp(&right.id));
    for definition in definitions {
        let signature = definition
            .signature
            .as_ref()
            .ok_or_else(|| format!("{} has no supported signature", definition.id))?;
        let parameters = signature
            .parameters
            .iter()
            .map(|parameter| {
                Ok(format!(
                    "arg{}: {}",
                    parameter.position,
                    render_type(
                        &parameter.type_ir,
                        &names,
                        &format!(
                            "definitions.{}.signature.parameters[{}].type",
                            definition.id, parameter.position
                        )
                    )?
                ))
            })
            .collect::<Result<Vec<_>, String>>()?
            .join(", ");
        writeln!(
            output,
            "export declare function {}({parameters}): {};",
            names.functions[&definition.id],
            render_type(
                &signature.result,
                &names,
                &format!("definitions.{}.signature.result", definition.id)
            )?
        )
        .expect("write to String");
    }
    Ok(output)
}

struct TypeScriptNames {
    declarations: BTreeMap<String, String>,
    functions: BTreeMap<String, String>,
}

impl TypeScriptNames {
    fn new(document: &Document) -> Result<Self, String> {
        let mut declarations = BTreeMap::new();
        let mut functions = BTreeMap::new();
        let mut seen_types = BTreeMap::new();
        let mut seen_functions = BTreeMap::new();
        for declaration in &document.declarations {
            let name = pascal(declaration.id())?;
            insert_unique(
                &mut seen_types,
                &name,
                declaration.id(),
                "TypeScript declaration",
            )?;
            declarations.insert(declaration.id().to_owned(), name);
        }
        for definition in &document.definitions {
            let name = snake(&definition.name)?;
            insert_unique(
                &mut seen_functions,
                &name,
                &definition.id,
                "TypeScript function",
            )?;
            functions.insert(definition.id.clone(), name);
        }
        Ok(Self {
            declarations,
            functions,
        })
    }
}

fn render_declaration(
    output: &mut String,
    declaration: &Declaration,
    names: &TypeScriptNames,
) -> Result<(), String> {
    let parameters = declaration
        .type_parameters()
        .iter()
        .map(|name| type_parameter(name))
        .collect::<Result<Vec<_>, _>>()?;
    let generics = if parameters.is_empty() {
        String::new()
    } else {
        format!("<{}>", parameters.join(", "))
    };
    match declaration {
        Declaration::Struct { id, fields, .. } => {
            writeln!(
                output,
                "export interface {}{generics} {{",
                names.declarations[id]
            )
            .expect("write to String");
            let mut seen = BTreeMap::new();
            for (index, field) in fields.iter().enumerate() {
                let field_name = snake(&field.name)?;
                insert_unique(
                    &mut seen,
                    &field_name,
                    &format!("{id}.{}", field.name),
                    "TypeScript field",
                )?;
                writeln!(
                    output,
                    "  readonly {field_name}: {};",
                    render_type(
                        &field.type_ir,
                        names,
                        &format!("declarations.{id}.fields[{index}].type")
                    )?
                )
                .expect("write to String");
            }
            output.push_str("}\n\n");
        }
        Declaration::Enum { id, variants, .. } => {
            writeln!(output, "export type {}{generics} =", names.declarations[id])
                .expect("write to String");
            let mut seen = BTreeMap::new();
            for (index, variant) in variants.iter().enumerate() {
                let variant_name = snake(&variant.name)?.replace('_', "-");
                insert_unique(
                    &mut seen,
                    &variant_name,
                    &format!("{id}.{}", variant.name),
                    "TypeScript variant",
                )?;
                let payload = variant
                    .payload
                    .iter()
                    .enumerate()
                    .map(|(payload_index, item)| {
                        render_type(
                            item,
                            names,
                            &format!(
                                "declarations.{id}.variants[{index}].payload[{payload_index}]"
                            ),
                        )
                    })
                    .collect::<Result<Vec<_>, _>>()?;
                let separator = if index == 0 { "  " } else { "  | " };
                if payload.is_empty() {
                    writeln!(output, "{separator}{{ readonly tag: {variant_name:?} }}")
                        .expect("write to String");
                } else {
                    writeln!(output, "{separator}{{ readonly tag: {variant_name:?}; readonly payload: readonly [{}] }}", payload.join(", ")).expect("write to String");
                }
            }
            output.push_str(";\n\n");
        }
    }
    Ok(())
}

fn render_type(type_ir: &Type, names: &TypeScriptNames, path: &str) -> Result<String, String> {
    match type_ir {
        Type::Unit => Ok("void".to_owned()),
        Type::Bool => Ok("boolean".to_owned()),
        Type::Number => Ok("number".to_owned()),
        Type::String => Ok("string".to_owned()),
        Type::Buffer => Ok("Uint8Array".to_owned()),
        Type::List { item } => Ok(format!(
            "ReadonlyArray<{}>",
            render_type(item, names, &format!("{path}.item"))?
        )),
        Type::Option { item } => Ok(format!(
            "{{ readonly tag: \"none\" }} | {{ readonly tag: \"some\"; readonly value: {} }}",
            render_type(item, names, &format!("{path}.item"))?
        )),
        Type::Result { ok, error } => Ok(format!(
            "{{ readonly tag: \"ok\"; readonly value: {} }} | {{ readonly tag: \"err\"; readonly error: {} }}",
            render_type(ok, names, &format!("{path}.ok"))?,
            render_type(error, names, &format!("{path}.error"))?
        )),
        Type::Struct { id, arguments } | Type::Enum { id, arguments } => {
            let name = names
                .declarations
                .get(id)
                .ok_or_else(|| format!("{path}: missing Interface IR declaration {id}"))?;
            if arguments.is_empty() {
                Ok(name.clone())
            } else {
                Ok(format!(
                    "{}<{}>",
                    name,
                    arguments
                        .iter()
                        .enumerate()
                        .map(|(index, argument)| {
                            render_type(argument, names, &format!("{path}.arguments[{index}]"))
                        })
                        .collect::<Result<Vec<_>, _>>()?
                        .join(", ")
                ))
            }
        }
        Type::TypeParameter { name } => type_parameter(name),
    }
}
