use std::collections::BTreeMap;
use std::fmt::Write;

use crate::names::{insert_unique, kebab};
use crate::{Declaration, Document, Type};

pub(crate) fn render(document: &Document) -> Result<String, String> {
    let names = WitNames::new(document)?;
    let package = kebab(&document.package)?;
    let mut output = String::new();
    writeln!(
        output,
        "// Generated by calcit-bindgen from Interface IR v{}. Do not edit.\npackage calcit:{package}@{};\n\ninterface {package} {{",
        document.version, document.package_version
    )
    .expect("write to String");
    let mut declarations = document.declarations.iter().collect::<Vec<_>>();
    declarations.sort_by(|left, right| left.id().cmp(right.id()));
    for declaration in declarations {
        render_declaration(&mut output, declaration, &names)?;
    }
    let mut definitions = document.definitions.iter().collect::<Vec<_>>();
    definitions.sort_by(|left, right| left.id.cmp(&right.id));
    for definition in definitions {
        let signature = definition
            .signature
            .as_ref()
            .ok_or_else(|| format!("{} has no supported signature", definition.id))?;
        let parameters = signature
            .parameters
            .iter()
            .map(|parameter| {
                let path = format!(
                    "definitions.{}.signature.parameters[{}].type",
                    definition.id, parameter.position
                );
                let value = render_type(&parameter.type_ir, &names, &path)?
                    .ok_or_else(|| format!("{path}: Unit is not a representable WIT parameter"))?;
                Ok(format!("arg{}: {value}", parameter.position))
            })
            .collect::<Result<Vec<_>, String>>()?
            .join(", ");
        let result_path = format!("definitions.{}.signature.result", definition.id);
        let result = render_type(&signature.result, &names, &result_path)?;
        writeln!(
            output,
            "  {}: func({parameters}){};",
            names.functions[&definition.id],
            result.map_or_else(String::new, |value| format!(" -> {value}"))
        )
        .expect("write to String");
    }
    writeln!(
        output,
        "}}\n\nworld {package}-world {{\n  export {package};\n}}"
    )
    .expect("write to String");
    Ok(output)
}

struct WitNames {
    declarations: BTreeMap<String, String>,
    functions: BTreeMap<String, String>,
}

impl WitNames {
    fn new(document: &Document) -> Result<Self, String> {
        let mut declarations = BTreeMap::new();
        let mut functions = BTreeMap::new();
        let mut seen_types = BTreeMap::new();
        let mut seen_functions = BTreeMap::new();
        for declaration in &document.declarations {
            if !declaration.type_parameters().is_empty() {
                return Err(format!(
                    "declarations.{}: generic declarations are not representable in WIT",
                    declaration.id()
                ));
            }
            let name = kebab(declaration.id())?;
            insert_unique(&mut seen_types, &name, declaration.id(), "WIT declaration")?;
            declarations.insert(declaration.id().to_owned(), name);
        }
        for definition in &document.definitions {
            let name = kebab(&definition.name)?;
            insert_unique(&mut seen_functions, &name, &definition.id, "WIT function")?;
            functions.insert(definition.id.clone(), name);
        }
        Ok(Self {
            declarations,
            functions,
        })
    }
}

fn render_declaration(
    output: &mut String,
    declaration: &Declaration,
    names: &WitNames,
) -> Result<(), String> {
    match declaration {
        Declaration::Struct { id, fields, .. } => {
            writeln!(output, "  record {} {{", names.declarations[id]).expect("write to String");
            let mut seen = BTreeMap::new();
            for (index, field) in fields.iter().enumerate() {
                let field_name = kebab(&field.name)?;
                insert_unique(
                    &mut seen,
                    &field_name,
                    &format!("{id}.{}", field.name),
                    "WIT field",
                )?;
                let path = format!("declarations.{id}.fields[{index}].type");
                let value = render_type(&field.type_ir, names, &path)?.ok_or_else(|| {
                    format!("{path}: Unit is not a representable WIT record field")
                })?;
                writeln!(output, "    {field_name}: {value},").expect("write to String");
            }
            output.push_str("  }\n\n");
        }
        Declaration::Enum { id, variants, .. } => {
            writeln!(output, "  variant {} {{", names.declarations[id]).expect("write to String");
            let mut seen = BTreeMap::new();
            for (index, variant) in variants.iter().enumerate() {
                let variant_name = kebab(&variant.name)?;
                insert_unique(
                    &mut seen,
                    &variant_name,
                    &format!("{id}.{}", variant.name),
                    "WIT variant",
                )?;
                let payload = variant
                    .payload
                    .iter()
                    .enumerate()
                    .map(|(payload_index, item)| {
                        let path =
                            format!("declarations.{id}.variants[{index}].payload[{payload_index}]");
                        render_type(item, names, &path)?.ok_or_else(|| {
                            format!("{path}: Unit is not a representable WIT variant payload")
                        })
                    })
                    .collect::<Result<Vec<_>, String>>()?;
                match payload.as_slice() {
                    [] => writeln!(output, "    {variant_name},"),
                    [value] => writeln!(output, "    {variant_name}({value}),"),
                    values => writeln!(output, "    {variant_name}(tuple<{}>),", values.join(", ")),
                }
                .expect("write to String");
            }
            output.push_str("  }\n\n");
        }
    }
    Ok(())
}

fn render_type(type_ir: &Type, names: &WitNames, path: &str) -> Result<Option<String>, String> {
    match type_ir {
        Type::Unit => Ok(None),
        Type::Bool => Ok(Some("bool".to_owned())),
        Type::Number => Ok(Some("float64".to_owned())),
        Type::String => Ok(Some("string".to_owned())),
        Type::Buffer => Ok(Some("list<u8>".to_owned())),
        Type::List { item } => Ok(Some(format!(
            "list<{}>",
            render_type(item, names, &format!("{path}.item"))?
                .ok_or_else(|| format!("{path}.item: Unit is not a representable WIT list item"))?
        ))),
        Type::Option { item } => Ok(Some(format!(
            "option<{}>",
            render_type(item, names, &format!("{path}.item"))?.ok_or_else(|| format!(
                "{path}.item: Unit is not a representable WIT option item"
            ))?
        ))),
        Type::Result { ok, error } => {
            let ok = render_type(ok, names, &format!("{path}.ok"))?;
            let error = render_type(error, names, &format!("{path}.error"))?;
            Ok(Some(match (ok, error) {
                (None, None) => "result".to_owned(),
                (Some(ok), None) => format!("result<{ok}>"),
                (None, Some(error)) => format!("result<_, {error}>"),
                (Some(ok), Some(error)) => format!("result<{ok}, {error}>"),
            }))
        }
        Type::Struct { id, arguments } | Type::Enum { id, arguments } => {
            if !arguments.is_empty() {
                return Err(format!(
                    "{path}: generic declaration application {id} is not representable in WIT"
                ));
            }
            Ok(Some(
                names
                    .declarations
                    .get(id)
                    .ok_or_else(|| format!("{path}: missing Interface IR declaration {id}"))?
                    .clone(),
            ))
        }
        Type::TypeParameter { name } => Err(format!(
            "{path}: type parameter {name} is not representable in WIT"
        )),
    }
}
