use std::collections::BTreeMap;
use std::fmt::Write;

use crate::names::{insert_unique, kebab};
use crate::{
    ComponentDirection, ComponentDocument, ComponentInvocation, Declaration, DefinitionStatus,
    Document, FunctionSignature, Type,
};

pub(crate) fn render(document: &Document) -> Result<String, String> {
    let names = WitNames::new(document)?;
    let package = kebab(&document.package)?;
    let mut output = String::new();
    writeln!(
        output,
        "// Generated by calcit-bindgen from Interface IR v{}. Do not edit.\npackage calcit:{package}@{};\n\ninterface {package} {{",
        document.version, document.package_version
    )
    .expect("write to String");
    let mut declarations = document.declarations.iter().collect::<Vec<_>>();
    declarations.sort_by(|left, right| left.id().cmp(right.id()));
    for declaration in declarations {
        render_declaration(&mut output, declaration, &names)?;
    }
    let mut definitions = document.definitions.iter().collect::<Vec<_>>();
    definitions.sort_by(|left, right| left.id.cmp(&right.id));
    for definition in definitions {
        let signature = definition
            .signature
            .as_ref()
            .ok_or_else(|| format!("{} has no supported signature", definition.id))?;
        let parameters = signature
            .parameters
            .iter()
            .map(|parameter| {
                let path = format!(
                    "definitions.{}.signature.parameters[{}].type",
                    definition.id, parameter.position
                );
                let value = render_type(&parameter.type_ir, &names, &path)?
                    .ok_or_else(|| format!("{path}: Unit is not a representable WIT parameter"))?;
                Ok(format!("arg{}: {value}", parameter.position))
            })
            .collect::<Result<Vec<_>, String>>()?
            .join(", ");
        let result_path = format!("definitions.{}.signature.result", definition.id);
        let result = render_type(&signature.result, &names, &result_path)?;
        writeln!(
            output,
            "  {}: func({parameters}){};",
            names.functions[&definition.id],
            result.map_or_else(String::new, |value| format!(" -> {value}"))
        )
        .expect("write to String");
    }
    writeln!(
        output,
        "}}\n\nworld {package}-world {{\n  export {package};\n}}"
    )
    .expect("write to String");
    Ok(output)
}

pub(crate) fn render_component(document: &ComponentDocument) -> Result<String, String> {
    let package = kebab(&document.package)?;
    let world = format!("{package}-world");
    let type_interface = format!("{package}-types");
    let type_names = ComponentWitNames::new(document)?;
    let mut imports = BTreeMap::<String, Vec<_>>::new();
    let mut exports = Vec::new();
    let mut binding_names = BTreeMap::new();
    let mut definitions = document.definitions.iter().collect::<Vec<_>>();
    definitions.sort_by(|left, right| left.id.cmp(&right.id));

    for definition in definitions {
        if definition.status != DefinitionStatus::Supported {
            return Err(format!(
                "definitions.{}: Component generation requires a supported definition",
                definition.id
            ));
        }
        let signature = definition.signature.as_ref().ok_or_else(|| {
            format!(
                "definitions.{}: supported Component definition has no signature",
                definition.id
            )
        })?;
        let symbol = exact_component_name(
            &definition.symbol,
            &format!("definitions.{}.symbol", definition.id),
        )?;
        match definition.direction {
            ComponentDirection::Import => {
                let module = definition.module.as_deref().ok_or_else(|| {
                    format!(
                        "definitions.{}: Component import has no module",
                        definition.id
                    )
                })?;
                let module_name =
                    exact_component_name(module, &format!("definitions.{}.module", definition.id))?;
                let identity = format!("import {module_name}/{symbol}");
                insert_unique(
                    &mut binding_names,
                    &identity,
                    &definition.id,
                    "Component binding",
                )?;
                imports.entry(module_name).or_default().push((
                    symbol,
                    definition.id.as_str(),
                    signature,
                    definition.invocation,
                ));
            }
            ComponentDirection::Export => {
                let identity = format!("export {symbol}");
                insert_unique(
                    &mut binding_names,
                    &identity,
                    &definition.id,
                    "Component binding",
                )?;
                exports.push((
                    symbol,
                    definition.id.as_str(),
                    signature,
                    definition.invocation,
                ));
            }
        }
    }

    let mut output = String::new();
    writeln!(
        output,
        "// Generated by calcit-bindgen from Component Interface IR v{}. Do not edit.\npackage calcit:{package}@{};\n",
        document.version, document.package_version
    )
    .expect("write to String");
    if !document.declarations.is_empty() {
        writeln!(output, "interface {type_interface} {{").expect("write to String");
        render_component_declarations(&mut output, document, &type_names)?;
        output.push_str("}\n\n");
    }
    writeln!(output, "world {world} {{").expect("write to String");
    render_component_type_use(&mut output, &type_interface, &type_names, "  ");
    for (module, functions) in imports {
        writeln!(output, "  import {module}: interface {{").expect("write to String");
        render_component_type_use(&mut output, &type_interface, &type_names, "    ");
        for (symbol, id, signature, invocation) in functions {
            writeln!(output, "    /// Calcit definition: {id}").expect("write to String");
            writeln!(
                output,
                "    {symbol}: {};",
                render_component_signature(signature, invocation, id, &type_names)?
            )
            .expect("write to String");
        }
        output.push_str("  }\n");
    }
    for (symbol, id, signature, invocation) in exports {
        writeln!(output, "  /// Calcit definition: {id}").expect("write to String");
        writeln!(
            output,
            "  export {symbol}: {};",
            render_component_signature(signature, invocation, id, &type_names)?
        )
        .expect("write to String");
    }
    output.push_str("}\n");
    Ok(output)
}

fn render_component_signature(
    signature: &FunctionSignature,
    invocation: Option<ComponentInvocation>,
    definition_id: &str,
    names: &ComponentWitNames,
) -> Result<String, String> {
    let parameters = signature
        .parameters
        .iter()
        .map(|parameter| {
            Ok(format!(
                "arg{}: {}",
                parameter.position,
                render_component_type(
                    &parameter.type_ir,
                    names,
                    &format!(
                        "definitions.{definition_id}.signature.parameters[{}].type",
                        parameter.position
                    )
                )?
            ))
        })
        .collect::<Result<Vec<_>, String>>()?
        .join(", ");
    let result_path = format!("definitions.{definition_id}.signature.result");
    let function = if invocation == Some(ComponentInvocation::Async) {
        "async func"
    } else {
        "func"
    };
    if matches!(signature.result, Type::Unit) {
        Ok(format!("{function}({parameters})"))
    } else {
        let result = render_component_type(&signature.result, names, &result_path)?;
        Ok(format!("{function}({parameters}) -> {result}"))
    }
}

fn render_component_type(
    type_ir: &Type,
    names: &ComponentWitNames,
    path: &str,
) -> Result<String, String> {
    match type_ir {
        Type::Bool => Ok("bool".to_owned()),
        Type::Buffer => Ok("list<u8>".to_owned()),
        Type::List { item } => Ok(format!(
            "list<{}>",
            render_component_type(item, names, &format!("{path}.item"))?
        )),
        Type::Number => Ok("f64".to_owned()),
        Type::Int8 => Ok("s8".to_owned()),
        Type::Uint8 => Ok("u8".to_owned()),
        Type::Int16 => Ok("s16".to_owned()),
        Type::Uint16 => Ok("u16".to_owned()),
        Type::Int32 => Ok("s32".to_owned()),
        Type::Uint32 => Ok("u32".to_owned()),
        Type::Int64 => Ok("s64".to_owned()),
        Type::Uint64 => Ok("u64".to_owned()),
        Type::Float32 => Ok("f32".to_owned()),
        Type::Float64 => Ok("f64".to_owned()),
        Type::Option { item } => Ok(format!(
            "option<{}>",
            render_component_type(item, names, &format!("{path}.item"))?
        )),
        Type::Result { ok, error } => {
            let ok = render_component_variant_payload(ok, names, &format!("{path}.ok"))?;
            let error = render_component_variant_payload(error, names, &format!("{path}.error"))?;
            Ok(match (ok, error) {
                (None, None) => "result".to_owned(),
                (Some(ok), None) => format!("result<{ok}>"),
                (None, Some(error)) => format!("result<_, {error}>"),
                (Some(ok), Some(error)) => format!("result<{ok}, {error}>"),
            })
        }
        Type::String => Ok("string".to_owned()),
        Type::Struct { id, arguments } => {
            if !arguments.is_empty() {
                return Err(format!(
                    "{path}: generic Struct application {id} is not representable in Component WIT"
                ));
            }
            names.declarations.get(id).cloned().ok_or_else(|| {
                format!("{path}: missing Component Interface IR Struct declaration {id}")
            })
        }
        Type::Enum { id, arguments } => {
            if !arguments.is_empty() {
                return Err(format!(
                    "{path}: generic Enum application {id} is not representable in Component WIT"
                ));
            }
            names.declarations.get(id).cloned().ok_or_else(|| {
                format!("{path}: missing Component Interface IR Enum declaration {id}")
            })
        }
        other => Err(format!(
            "{path}: Component packaging currently supports only Unit results, Bool, Buffer, recursive List<T>, Number, Option<T>, Result<T, E>, String, monomorphic Struct records, and closed monomorphic Enum variants, received {other:?}"
        )),
    }
}

fn render_component_variant_payload(
    type_ir: &Type,
    names: &ComponentWitNames,
    path: &str,
) -> Result<Option<String>, String> {
    if matches!(type_ir, Type::Unit) {
        Ok(None)
    } else {
        render_component_type(type_ir, names, path).map(Some)
    }
}

struct ComponentWitNames {
    declarations: BTreeMap<String, String>,
}

impl ComponentWitNames {
    fn new(document: &ComponentDocument) -> Result<Self, String> {
        let mut declarations = BTreeMap::new();
        let mut seen = BTreeMap::new();
        for declaration in &document.declarations {
            let id = declaration.id();
            let type_parameters = declaration.type_parameters();
            if !type_parameters.is_empty() {
                return Err(format!(
                    "declarations.{id}.type_parameters: generic {} declarations are not representable in Component WIT",
                    declaration.kind()
                ));
            }
            let wit_name = escape_wit_keyword(kebab(id)?);
            insert_unique(&mut seen, &wit_name, id, "Component WIT declaration")?;
            declarations.insert(id.to_owned(), wit_name);
        }
        Ok(Self { declarations })
    }
}

fn render_component_declarations(
    output: &mut String,
    document: &ComponentDocument,
    names: &ComponentWitNames,
) -> Result<(), String> {
    let mut declarations = document.declarations.iter().collect::<Vec<_>>();
    declarations.sort_by(|left, right| left.id().cmp(right.id()));
    for declaration in declarations {
        match declaration {
            Declaration::Struct { id, fields, .. } => {
                writeln!(output, "  record {} {{", names.declarations[id])
                    .expect("write to String");
                let mut seen = BTreeMap::new();
                for (index, field) in fields.iter().enumerate() {
                    let path = format!("declarations.{id}.fields[{index}]");
                    let field_name = exact_component_name(&field.name, &format!("{path}.name"))?;
                    insert_unique(
                        &mut seen,
                        &field_name,
                        &format!("{id}.{}", field.name),
                        "Component WIT field",
                    )?;
                    if matches!(field.type_ir, Type::Unit) {
                        return Err(format!(
                            "{path}.type: Unit is not a representable Component WIT record field"
                        ));
                    }
                    let value =
                        render_component_type(&field.type_ir, names, &format!("{path}.type"))?;
                    writeln!(output, "    {field_name}: {value},").expect("write to String");
                }
            }
            Declaration::Enum { id, variants, .. } => {
                writeln!(output, "  variant {} {{", names.declarations[id])
                    .expect("write to String");
                let mut seen = BTreeMap::new();
                for (index, variant) in variants.iter().enumerate() {
                    let path = format!("declarations.{id}.variants[{index}]");
                    let case_name = exact_component_name(&variant.name, &format!("{path}.name"))?;
                    insert_unique(
                        &mut seen,
                        &case_name,
                        &format!("{id}.{}", variant.name),
                        "Component WIT variant",
                    )?;
                    let payload = variant
                        .payload
                        .iter()
                        .enumerate()
                        .map(|(payload_index, value)| {
                            let payload_path = format!("{path}.payload[{payload_index}]");
                            if matches!(value, Type::Unit) {
                                return Err(format!(
                                    "{payload_path}: Unit is not a representable Component WIT variant payload; omit the payload instead"
                                ));
                            }
                            render_component_type(value, names, &payload_path)
                        })
                        .collect::<Result<Vec<_>, String>>()?;
                    match payload.as_slice() {
                        [] => writeln!(output, "    {case_name},"),
                        [value] => writeln!(output, "    {case_name}({value}),"),
                        values => {
                            writeln!(output, "    {case_name}(tuple<{}>),", values.join(", "))
                        }
                    }
                    .expect("write to String");
                }
            }
        }
        output.push_str("  }\n");
    }
    Ok(())
}

fn render_component_type_use(
    output: &mut String,
    type_interface: &str,
    names: &ComponentWitNames,
    indentation: &str,
) {
    if names.declarations.is_empty() {
        return;
    }
    let declarations = names
        .declarations
        .values()
        .cloned()
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        output,
        "{indentation}use {type_interface}.{{{declarations}}};"
    )
    .expect("write to String");
}

fn exact_component_name(value: &str, path: &str) -> Result<String, String> {
    let wit_name = kebab(value)?;
    if wit_name != value {
        return Err(format!(
            "{path}: Component ABI name {value:?} is not a canonical WIT identifier; refusing to rewrite binding identity as {wit_name:?}"
        ));
    }
    Ok(escape_wit_keyword(wit_name))
}

fn escape_wit_keyword(value: String) -> String {
    if matches!(
        value.as_str(),
        "use"
            | "type"
            | "func"
            | "u8"
            | "u16"
            | "u32"
            | "u64"
            | "s8"
            | "s16"
            | "s32"
            | "s64"
            | "f32"
            | "f64"
            | "char"
            | "record"
            | "resource"
            | "own"
            | "borrow"
            | "flags"
            | "variant"
            | "enum"
            | "bool"
            | "string"
            | "option"
            | "result"
            | "future"
            | "stream"
            | "error-context"
            | "list"
            | "map"
            | "_"
            | "as"
            | "from"
            | "static"
            | "interface"
            | "tuple"
            | "import"
            | "export"
            | "world"
            | "package"
            | "constructor"
            | "include"
            | "with"
            | "async"
    ) {
        format!("%{value}")
    } else {
        value
    }
}

struct WitNames {
    declarations: BTreeMap<String, String>,
    functions: BTreeMap<String, String>,
}

impl WitNames {
    fn new(document: &Document) -> Result<Self, String> {
        let mut declarations = BTreeMap::new();
        let mut functions = BTreeMap::new();
        let mut seen_types = BTreeMap::new();
        let mut seen_functions = BTreeMap::new();
        for declaration in &document.declarations {
            if !declaration.type_parameters().is_empty() {
                return Err(format!(
                    "declarations.{}: generic declarations are not representable in WIT",
                    declaration.id()
                ));
            }
            let name = kebab(declaration.id())?;
            insert_unique(&mut seen_types, &name, declaration.id(), "WIT declaration")?;
            declarations.insert(declaration.id().to_owned(), name);
        }
        for definition in &document.definitions {
            let name = kebab(&definition.name)?;
            insert_unique(&mut seen_functions, &name, &definition.id, "WIT function")?;
            functions.insert(definition.id.clone(), name);
        }
        Ok(Self {
            declarations,
            functions,
        })
    }
}

fn render_declaration(
    output: &mut String,
    declaration: &Declaration,
    names: &WitNames,
) -> Result<(), String> {
    match declaration {
        Declaration::Struct { id, fields, .. } => {
            writeln!(output, "  record {} {{", names.declarations[id]).expect("write to String");
            let mut seen = BTreeMap::new();
            for (index, field) in fields.iter().enumerate() {
                let field_name = kebab(&field.name)?;
                insert_unique(
                    &mut seen,
                    &field_name,
                    &format!("{id}.{}", field.name),
                    "WIT field",
                )?;
                let path = format!("declarations.{id}.fields[{index}].type");
                let value = render_type(&field.type_ir, names, &path)?.ok_or_else(|| {
                    format!("{path}: Unit is not a representable WIT record field")
                })?;
                writeln!(output, "    {field_name}: {value},").expect("write to String");
            }
            output.push_str("  }\n\n");
        }
        Declaration::Enum { id, variants, .. } => {
            writeln!(output, "  variant {} {{", names.declarations[id]).expect("write to String");
            let mut seen = BTreeMap::new();
            for (index, variant) in variants.iter().enumerate() {
                let variant_name = kebab(&variant.name)?;
                insert_unique(
                    &mut seen,
                    &variant_name,
                    &format!("{id}.{}", variant.name),
                    "WIT variant",
                )?;
                let payload = variant
                    .payload
                    .iter()
                    .enumerate()
                    .map(|(payload_index, item)| {
                        let path =
                            format!("declarations.{id}.variants[{index}].payload[{payload_index}]");
                        render_type(item, names, &path)?.ok_or_else(|| {
                            format!("{path}: Unit is not a representable WIT variant payload")
                        })
                    })
                    .collect::<Result<Vec<_>, String>>()?;
                match payload.as_slice() {
                    [] => writeln!(output, "    {variant_name},"),
                    [value] => writeln!(output, "    {variant_name}({value}),"),
                    values => writeln!(output, "    {variant_name}(tuple<{}>),", values.join(", ")),
                }
                .expect("write to String");
            }
            output.push_str("  }\n\n");
        }
    }
    Ok(())
}

fn render_type(type_ir: &Type, names: &WitNames, path: &str) -> Result<Option<String>, String> {
    match type_ir {
        Type::Unit => Ok(None),
        Type::Bool => Ok(Some("bool".to_owned())),
        Type::Number => Ok(Some("f64".to_owned())),
        Type::Int8 => Ok(Some("s8".to_owned())),
        Type::Uint8 => Ok(Some("u8".to_owned())),
        Type::Int16 => Ok(Some("s16".to_owned())),
        Type::Uint16 => Ok(Some("u16".to_owned())),
        Type::Int32 => Ok(Some("s32".to_owned())),
        Type::Uint32 => Ok(Some("u32".to_owned())),
        Type::Int64 => Ok(Some("s64".to_owned())),
        Type::Uint64 => Ok(Some("u64".to_owned())),
        Type::Float32 => Ok(Some("f32".to_owned())),
        Type::Float64 => Ok(Some("f64".to_owned())),
        Type::String => Ok(Some("string".to_owned())),
        Type::Buffer => Ok(Some("list<u8>".to_owned())),
        Type::List { item } => Ok(Some(format!(
            "list<{}>",
            render_type(item, names, &format!("{path}.item"))?
                .ok_or_else(|| format!("{path}.item: Unit is not a representable WIT list item"))?
        ))),
        Type::Option { item } => Ok(Some(format!(
            "option<{}>",
            render_type(item, names, &format!("{path}.item"))?.ok_or_else(|| format!(
                "{path}.item: Unit is not a representable WIT option item"
            ))?
        ))),
        Type::Result { ok, error } => {
            let ok = render_type(ok, names, &format!("{path}.ok"))?;
            let error = render_type(error, names, &format!("{path}.error"))?;
            Ok(Some(match (ok, error) {
                (None, None) => "result".to_owned(),
                (Some(ok), None) => format!("result<{ok}>"),
                (None, Some(error)) => format!("result<_, {error}>"),
                (Some(ok), Some(error)) => format!("result<{ok}, {error}>"),
            }))
        }
        Type::Struct { id, arguments } | Type::Enum { id, arguments } => {
            if !arguments.is_empty() {
                return Err(format!(
                    "{path}: generic declaration application {id} is not representable in WIT"
                ));
            }
            Ok(Some(
                names
                    .declarations
                    .get(id)
                    .ok_or_else(|| format!("{path}: missing Interface IR declaration {id}"))?
                    .clone(),
            ))
        }
        Type::TypeParameter { name } => Err(format!(
            "{path}: type parameter {name} is not representable in WIT"
        )),
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::{ComponentWitNames, render_component, render_component_type};
    use crate::{
        ComponentDefinition, ComponentDirection, ComponentDocument, ComponentInvocation,
        Declaration, DefinitionStatus, EnumVariant, FunctionSignature, Parameter, StructField,
        Type,
    };

    #[test]
    fn component_v3_async_invocation_renders_native_async_wit() {
        let document = ComponentDocument {
            version: 3,
            package: "demo".to_owned(),
            package_version: "0.0.0".to_owned(),
            declarations: vec![],
            definitions: vec![
                ComponentDefinition {
                    id: "app.main/fetch".to_owned(),
                    namespace: "app.main".to_owned(),
                    name: "fetch".to_owned(),
                    doc: String::new(),
                    logical_schema: String::new(),
                    direction: ComponentDirection::Export,
                    invocation: Some(ComponentInvocation::Async),
                    module: None,
                    symbol: "fetch".to_owned(),
                    signature: Some(FunctionSignature {
                        parameters: vec![],
                        result: Type::String,
                    }),
                    status: DefinitionStatus::Supported,
                    diagnostic_codes: vec![],
                },
                ComponentDefinition {
                    id: "app.main/load".to_owned(),
                    namespace: "app.main".to_owned(),
                    name: "load".to_owned(),
                    doc: String::new(),
                    logical_schema: String::new(),
                    direction: ComponentDirection::Import,
                    invocation: Some(ComponentInvocation::Async),
                    module: Some("host-storage".to_owned()),
                    symbol: "load".to_owned(),
                    signature: Some(FunctionSignature {
                        parameters: vec![Parameter {
                            position: 0,
                            type_ir: Type::String,
                        }],
                        result: Type::String,
                    }),
                    status: DefinitionStatus::Supported,
                    diagnostic_codes: vec![],
                },
                ComponentDefinition {
                    id: "app.main/version".to_owned(),
                    namespace: "app.main".to_owned(),
                    name: "version".to_owned(),
                    doc: String::new(),
                    logical_schema: String::new(),
                    direction: ComponentDirection::Export,
                    invocation: Some(ComponentInvocation::Sync),
                    module: None,
                    symbol: "version".to_owned(),
                    signature: Some(FunctionSignature {
                        parameters: vec![],
                        result: Type::String,
                    }),
                    status: DefinitionStatus::Supported,
                    diagnostic_codes: vec![],
                },
            ],
        };

        let wit = render_component(&document).expect("async Component invocation should render");
        assert!(
            wit.contains("export fetch: async func() -> string;"),
            "{wit}"
        );
        assert!(
            wit.contains("load: async func(arg0: string) -> string;"),
            "{wit}"
        );
        assert!(wit.contains("export version: func() -> string;"), "{wit}");
        let mut resolve = wit_parser::Resolve::default();
        resolve
            .push_str("component-async.wit", &wit)
            .expect("generated WASI 0.3 async WIT should parse");
    }

    #[test]
    fn component_type_rendering_is_recursive_and_keeps_payload_paths() {
        let names = ComponentWitNames {
            declarations: BTreeMap::new(),
        };
        let nested = Type::List {
            item: Box::new(Type::List {
                item: Box::new(Type::Number),
            }),
        };
        assert_eq!(
            render_component_type(&nested, &names, "definitions.demo.signature.result"),
            Ok("list<list<f64>>".to_owned())
        );

        let unsupported = Type::List {
            item: Box::new(Type::List {
                item: Box::new(Type::Unit),
            }),
        };
        let error =
            render_component_type(&unsupported, &names, "definitions.demo.signature.result")
                .expect_err("nested Unit must not degrade to a Dynamic WIT type");
        assert!(error.contains("definitions.demo.signature.result.item.item"));

        let result = Type::Result {
            ok: Box::new(Type::List {
                item: Box::new(Type::Number),
            }),
            error: Box::new(Type::String),
        };
        assert_eq!(
            render_component_type(&result, &names, "definitions.demo.signature.result"),
            Ok("result<list<f64>, string>".to_owned())
        );

        let numeric = Type::Result {
            ok: Box::new(Type::List {
                item: Box::new(Type::Uint16),
            }),
            error: Box::new(Type::Option {
                item: Box::new(Type::Float32),
            }),
        };
        assert_eq!(
            render_component_type(&numeric, &names, "definitions.demo.signature.result"),
            Ok("result<list<u16>, option<f32>>".to_owned())
        );

        let scalar_cases = [
            (Type::Int8, "s8"),
            (Type::Uint8, "u8"),
            (Type::Int16, "s16"),
            (Type::Uint16, "u16"),
            (Type::Int32, "s32"),
            (Type::Uint32, "u32"),
            (Type::Int64, "s64"),
            (Type::Uint64, "u64"),
            (Type::Float32, "f32"),
            (Type::Float64, "f64"),
        ];
        for (type_ir, expected) in scalar_cases {
            assert_eq!(
                render_component_type(&type_ir, &names, "definitions.demo.signature.result"),
                Ok(expected.to_owned())
            );
        }

        let unsupported = Type::Option {
            item: Box::new(Type::Struct {
                id: "demo/Person".to_owned(),
                arguments: vec![],
            }),
        };
        let error =
            render_component_type(&unsupported, &names, "definitions.demo.signature.result")
                .expect_err("missing Struct declaration must keep its schema path");
        assert!(error.contains("definitions.demo.signature.result.item"));
    }

    #[test]
    fn component_structs_render_as_shared_named_records() {
        let profile_type = Type::Struct {
            id: "app.main/Profile".to_owned(),
            arguments: vec![],
        };
        let document = ComponentDocument {
            version: 2,
            package: "demo".to_owned(),
            package_version: "0.0.0".to_owned(),
            declarations: vec![Declaration::Struct {
                id: "app.main/Profile".to_owned(),
                namespace: "app.main".to_owned(),
                name: "Profile".to_owned(),
                type_parameters: vec![],
                fields: vec![
                    StructField {
                        name: "name".to_owned(),
                        type_ir: Type::String,
                    },
                    StructField {
                        name: "scores".to_owned(),
                        type_ir: Type::List {
                            item: Box::new(Type::Number),
                        },
                    },
                    StructField {
                        name: "maybe-name".to_owned(),
                        type_ir: Type::Option {
                            item: Box::new(Type::String),
                        },
                    },
                    StructField {
                        name: "outcome".to_owned(),
                        type_ir: Type::Result {
                            ok: Box::new(Type::List {
                                item: Box::new(Type::Number),
                            }),
                            error: Box::new(Type::String),
                        },
                    },
                ],
            }],
            definitions: vec![ComponentDefinition {
                id: "app.main/echo-profile".to_owned(),
                namespace: "app.main".to_owned(),
                name: "echo-profile".to_owned(),
                doc: String::new(),
                logical_schema: String::new(),
                direction: ComponentDirection::Export,
                invocation: None,
                module: None,
                symbol: "echo-profile".to_owned(),
                signature: Some(FunctionSignature {
                    parameters: vec![Parameter {
                        position: 0,
                        type_ir: profile_type.clone(),
                    }],
                    result: profile_type,
                }),
                status: DefinitionStatus::Supported,
                diagnostic_codes: vec![],
            }],
        };
        let wit = render_component(&document).expect("render Component Struct WIT");
        assert!(wit.contains("interface demo-types {\n  record app-main-profile {"));
        assert!(wit.contains("    name: string,\n    scores: list<f64>,"));
        assert!(wit.contains("    maybe-name: option<string>,"));
        assert!(wit.contains("    outcome: result<list<f64>, string>,"));
        assert!(wit.contains("use demo-types.{app-main-profile};"));
        assert!(wit.contains("echo-profile: func(arg0: app-main-profile) -> app-main-profile;"));
        wit_parser::Resolve::default()
            .push_str("component-struct.wit", &wit)
            .expect("generated Component Struct WIT must parse");
    }

    #[test]
    fn component_enums_render_closed_ordered_variants() {
        let event_type = Type::Enum {
            id: "app.main/Event".to_owned(),
            arguments: vec![],
        };
        let document = ComponentDocument {
            version: 2,
            package: "demo".to_owned(),
            package_version: "0.0.0".to_owned(),
            declarations: vec![
                Declaration::Enum {
                    id: "app.main/Event".to_owned(),
                    namespace: "app.main".to_owned(),
                    name: "Event".to_owned(),
                    type_parameters: vec![],
                    variants: vec![
                        EnumVariant {
                            name: "idle".to_owned(),
                            payload: vec![],
                        },
                        EnumVariant {
                            name: "moved".to_owned(),
                            payload: vec![Type::Number, Type::Number],
                        },
                        EnumVariant {
                            name: "named".to_owned(),
                            payload: vec![Type::String],
                        },
                        EnumVariant {
                            name: "profile".to_owned(),
                            payload: vec![Type::Struct {
                                id: "app.main/Profile".to_owned(),
                                arguments: vec![],
                            }],
                        },
                    ],
                },
                Declaration::Struct {
                    id: "app.main/Profile".to_owned(),
                    namespace: "app.main".to_owned(),
                    name: "Profile".to_owned(),
                    type_parameters: vec![],
                    fields: vec![StructField {
                        name: "name".to_owned(),
                        type_ir: Type::String,
                    }],
                },
            ],
            definitions: vec![ComponentDefinition {
                id: "app.main/echo-event".to_owned(),
                namespace: "app.main".to_owned(),
                name: "echo-event".to_owned(),
                doc: String::new(),
                logical_schema: String::new(),
                direction: ComponentDirection::Export,
                invocation: None,
                module: None,
                symbol: "echo-event".to_owned(),
                signature: Some(FunctionSignature {
                    parameters: vec![Parameter {
                        position: 0,
                        type_ir: event_type.clone(),
                    }],
                    result: event_type,
                }),
                status: DefinitionStatus::Supported,
                diagnostic_codes: vec![],
            }],
        };
        let wit = render_component(&document).expect("render Component Enum WIT");
        assert!(wit.contains(
            "variant app-main-event {\n    idle,\n    moved(tuple<f64, f64>),\n    named(string),\n    profile(app-main-profile),\n  }"
        ));
        assert!(wit.contains("echo-event: func(arg0: app-main-event) -> app-main-event;"));
        wit_parser::Resolve::default()
            .push_str("component-enum.wit", &wit)
            .expect("generated Component Enum WIT must parse");

        let mut invalid = document;
        let Declaration::Enum { variants, .. } = &mut invalid.declarations[0] else {
            unreachable!("test declaration is an Enum")
        };
        variants[1].payload[0] = Type::Unit;
        let error = render_component(&invalid).expect_err("Unit Enum payload must fail");
        assert!(error.contains("declarations.app.main/Event.variants[1].payload[0]"));
        assert!(error.contains("omit the payload"));
    }
}
